### ISSUE TITLE
File write support

### ISSUE THREAD

**Issue by xc0z** [syrsly/StreamlabsChatbotSmartRegex#2]
If possible, it would be super awesome to have the ability to write a file based on a regex find.... or is there documentation i'm missing?

If not possible, that's alright. Thanks anyway :)

**Comment by syrsly** [comment]
There are some built-in functions in Python to write to text files fairly easily. I'm not sure what limitations exist for Streamlabs Chatbot, but I know it's possible to write to files. This is something you'll have to research and figure out on your own unless you'd like to commission the work to be done. However, I will be honest, I've never had a need to save to a file in Python outside of a PyGame save slot system many, many years ago. I'd have top research how to save files, too! lol

If you have any concerns, feel free to ask, and if you wish to commission work and want the quickest response, contact me directly via my twitter: https://twitter.com/SyrslyWasTaken

I'm closing this ticket, but again, feel free to contact me if you'd like to commission work to be done or just wish to chat about the possibilities for this script. I can also recommend alternative chatbots/apps if you need something that's not feasible with this script. Have a good weekend!

**Comment by syrsly** [comment]
My Twitter account has been deleted for many months now. Contact me on [Bluesky](https://bsky.app/profile/syrsly.com) if you need any help with my scripts going forward. I also check emails daily at syrsly@syrsly.com.
